name: Runners
on: workflow_dispatch
jobs:
    unix-job:
        name: Running on unix
        runs-on: self-hosted
        steps:
            - run: echo "Hello World unix"
    mac-job:
        name: Running on mac
        runs-on: mac-latest
        steps:
            - run: echo "Hello World unix"
